import ForgeCore

extension CommandRegistry {
    /// The built-in command catalog. Every entry here must appear in FEATURES.md or be
    /// infrastructure (document/edit/help).
    public static let standard: CommandRegistry = {
        var r = CommandRegistry()
        // session
        r.register(DocumentNew.self)
        r.register(DocumentList.self)
        r.register(DocumentActivate.self)
        r.register(DocumentClose.self)
        r.register(DocumentState.self)
        r.register(DocumentSave.self)
        r.register(DocumentOpen.self)
        r.register(EditUndo.self)
        r.register(EditRedo.self)
        r.register(TransactionBegin.self)
        r.register(TransactionCommit.self)
        r.register(TransactionRollback.self)
        // discovery
        r.register(HelpListCommands.self)
        r.register(HelpDescribeCommand.self)
        r.register(HelpSearchCommands.self)
        // sketches
        r.register(SketchCreate.self)
        r.register(SketchEdit.self)
        r.register(SketchExit.self)
        r.register(SketchRemove.self)
        r.register(SketchGet.self)
        r.register(SketchCheck.self)
        r.register(SketchAddPoint.self)
        r.register(SketchAddLine.self)
        r.register(SketchAddCircle.self)
        r.register(SketchAddArc.self)
        r.register(SketchAddEllipse.self)
        r.register(SketchAddSpline.self)
        r.register(SketchAddRectangle.self)
        r.register(SketchAddSlot.self)
        r.register(SketchAddPolygon.self)
        r.register(SketchAddRelation.self)
        r.register(SketchAddDimension.self)
        r.register(SketchSetDimension.self)
        r.register(SketchDelete.self)
        r.register(SketchDrag.self)
        r.register(SketchSetConstruction.self)
        r.register(SketchFillet.self)
        r.register(SketchChamfer.self)
        r.register(SketchMirror.self)
        r.register(SketchPatternLinear.self)
        r.register(SketchPatternCircular.self)
        r.register(SketchTrim.self)
        r.register(SketchExtend.self)
        r.register(SketchOffset.self)
        r.register(SketchMove.self)
        r.register(SketchRotate.self)
        r.register(SketchScale.self)
        r.register(SketchSplit.self)
        // bodies
        r.register(BodyCreateBox.self)
        r.register(BodyCreateCylinder.self)
        r.register(BodyCreateSphere.self)
        r.register(BodyCreateCone.self)
        r.register(BodyCreateTorus.self)
        r.register(BodyExtrude.self)
        r.register(BodyRevolve.self)
        r.register(BodyBoolean.self)
        r.register(BodyTransform.self)
        r.register(BodyFilletEdges.self)
        r.register(BodyDelete.self)
        r.register(BodyRename.self)
        // queries
        r.register(QueryBodies.self)
        r.register(QueryFaces.self)
        r.register(QueryEdges.self)
        r.register(QueryEntity.self)
        r.register(QueryMassProperties.self)
        r.register(QueryMeasure.self)
        r.register(QueryValidate.self)
        r.register(QueryCompareToSpec.self)
        // selection
        r.register(SelectionSet.self)
        r.register(SelectionGet.self)
        r.register(SelectionClear.self)
        // view
        r.register(ViewRender.self)
        r.register(ViewRenderMultiview.self)
        r.register(ViewPick.self)
        // export
        r.register(ExportSTEP.self)
        r.register(ExportSTL.self)
        return r
    }()
}
